name: Schedule-test

on:
  push:
  schedule:
      - cron: "0 11 * * *"

jobs: 
  job1:
    name: Schedule
    runs-on: ubuntu-latest
    steps:
    - name: Step01
      uses: actions/checkout@v2
      with:
        ref: main 
        
    - name: Step02
      run: ls -la
  job2:
    name: Schedule2
    runs-on: ubuntu-latest
    steps:
    - name: Step01
      uses: actions/checkout@v2
      with:
        ref: test
      
    - name: Step02
      run: ls -la
