name: Schedule

on:
  push:
  schedule:
      - cron: "0 20 * * *"
jobs: 
  build:
    name: Schedule
    runs-on: ubuntu-latest
    steps:
    - name: Step01
      uses: actions/checkout@v2
      
    - name: Step02
      run: ls -la
