name: Test00
on:
  pull_request:
    types: [closed]
    branches: 
      - main


jobs: 
  build:
    name: Test00
    runs-on: ubuntu-latest
    steps:
    - name: Step01
      uses: actions/checkout@v2
      
    - name: Step02
      run: ls -la

    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: abrams1101
        repo: testnew
        github_token: ${{ secrets.G_ACCESS_TOKEN }}
        workflow_file_name: test00.yml

    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: abrams1101
        repo: testnew
        ref: dev
        github_token: ${{ secrets.G_ACCESS_TOKEN }}
        workflow_file_name: test00.yml
