name: Deploy to ECR

on:
 
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  
  build:
    if: ${{ github.event.pull_request.merged }}
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
   
    - name: Trigger AWS CodePipeline
      uses: zulhfreelancer/aws-codepipeline-action@vX.X.X
      with:
        aws-region: "us-east-1"
        aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
        aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
        pipeline-name: "your-pipeline-name"
