name: Trigger Pipeline


on:
 
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  
  build:
    if: ${{ github.event.pull_request.merged }}
    name: Build Image
    runs-on: ubuntu-latest

    steps:
   
    - name: Trigger AWS CodePipeline
      uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
      with:
        aws-region: "us-east-1"
        aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
        aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
        pipeline-name: "test-codepipeline"
